# Generated by Django 3.2.18 on 2023-03-02 13:01

from django.db import migrations

from image_browser.builtin_plans import basic_plan, premium_plan, enterprise_plan


class Migration(migrations.Migration):
    dependencies = [
        ('image_browser', '0001_initial'),
    ]

    def insert_default_plans(apps, schema_editor):
        ThumbnailSize = apps.get_model('image_browser', 'ThumbnailSize')
        size_200 = ThumbnailSize(height=200, width=0)
        size_400 = ThumbnailSize(height=400, width=0)
        size_200.save()
        size_400.save()

        PlanTier = apps.get_model('image_browser', 'PlanTier')
        basic_plan_obj = PlanTier(name=basic_plan.name,
                                  show_original_link=basic_plan.show_original_link,
                                  create_expiring_link=basic_plan.create_expiring_link)
        premium_plan_obj = PlanTier(name=premium_plan.name,
                                    show_original_link=premium_plan.show_original_link,
                                    create_expiring_link=premium_plan.create_expiring_link)
        enterprise_plan_obj = PlanTier(name=enterprise_plan.name,
                                       show_original_link=enterprise_plan.show_original_link,
                                       create_expiring_link=enterprise_plan.create_expiring_link)

        basic_plan_obj.save()
        basic_plan_obj.thumbnail_sizes.set([size_200])
        premium_plan_obj.save()
        premium_plan_obj.thumbnail_sizes.set([size_200, size_400])
        enterprise_plan_obj.save()
        enterprise_plan_obj.thumbnail_sizes.set([size_200, size_400])
        print(enterprise_plan_obj)

    operations = [
        migrations.RunPython(insert_default_plans),
    ]
