# Generated by Django 4.1.7 on 2023-02-24 14:58

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinstance',
            name='image_file',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=''),
        ),
    ]
